### ISSUE TITLE
Improve global vars to project:build.gradle

### ISSUE THREAD

**Issue by JoaquimLey** [JoaquimLey/avenging#9]
Some variables (such as `compileSdkVersion` and `buildToolsVersion`) don't need to be secret therefore shouldn't/don't need to be on `gradle.settings`
## Context

With the current situation we have a (very) verbose `build.gradle` and unnecessary CI variables.
## Process

Does not apply.
## Expected result

Does not apply
## Current result

Does not apply
## Possible Fix

After passing to the project's `build.gradle` like this: 

```
    ext.buildToolsVer = '24.0.0'
    ext.androidSupportVer = '24.1.1'
    ext.googlePlayServicesVer = '9.0.2'
```

We can remove both the CI variables and verbose `build.gradle` variables.
### Tasks to keep track of this enhancement:
- [x] Move variables from `gradle.properties` to `project:build.gradle`
- [x] Get variables from `project:build.gradle` from both **mobile** and **wear** modules
- [x] Update `README.MD`
- [x] Remove CI variables (this is outside of the project scope)
- [x] Update CI (.travis.yml) to accept licenses

> - What went wrong:
>   A problem occurred configuring project ':core'.
>   > You have not accepted the license agreements of the following SDK components:
>   [Android SDK Build-Tools 24.0.2].
>   Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
>   Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
